version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - depguard
    - durationcheck
    - govet
    - ineffassign
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unused
  settings:
    depguard:
      rules:
        core-no-exec:
          files:
            - internal/core/**/*.go
          deny:
            - pkg: os/exec
              desc: Core layer must be pure. Use effects pattern and adapters for I/O.
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1005
        - -ST1020
        - -ST1022
        - -QF1002
        - -QF1003
        - -QF1007
  exclusions:
    generated: lax
    rules:
      - linters:
          - unused
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/example/orc
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
